### ISSUE TITLE
VW server changes?

### ISSUE THREAD

**Issue by Halbamy** [SushiTee/vwkommi#3]
I did have a check for my kommision number as chron job for a few months now, but it stopped working today.
I cannot even get the prefix with anymore
python3 -m vwkommi request -f XXYYYY

Anybody else having that issue?

**Comment by Halbamy** [comment]
After changing to the new URLs and adding "User-Agent": 'Chrome v22.2 Linux Ubuntu' to the header it works again

**Comment by SushiTee** [comment]
Thanks for the pull request.

I also noticed that you have to accept the terms of use of VW before being able to login with the usual method. The simple fix is to login via browser once.

I added a print to hint at that in 8154acd342840b410ee3af74c5bd14e968298602
